# Generated by Django 3.2.8 on 2021-12-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211217_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
