# Generated by Django 3.2.8 on 2021-11-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default_profile_picture.png', null=True, upload_to='profiles/'),
        ),
    ]
