# Generated by Django 3.2.8 on 2021-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profiles/default_profile_picture.png', null=True, upload_to='media/profiles/'),
        ),
    ]
