# Generated by Django 3.2.8 on 2021-11-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0010_alter_books_profile_image'),
        ('authentication', '0010_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite',
            field=models.ManyToManyField(to='bookmanage.books'),
        ),
    ]
