# Generated by Django 3.2.8 on 2021-12-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_auto_20211213_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online',
            field=models.CharField(choices=[('0', 'offline'), ('1', 'online')], default=('0', 'offline'), max_length=200),
        ),
    ]
