# Generated by Django 3.2.8 on 2021-10-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='buy',
            field=models.CharField(choices=[('0', 'sell'), ('1', 'rent'), ('2', 'gift')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/books-default.png', null=True, upload_to='profiles/'),
        ),
    ]
