# Generated by Django 3.2.8 on 2021-10-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0002_auto_20211028_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='user',
            new_name='owner',
        ),
    ]
