# Generated by Django 3.2.8 on 2021-10-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0006_alter_books_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
