# Generated by Django 3.2.8 on 2021-11-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0007_alter_books_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
