# Generated by Django 3.2.8 on 2021-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0008_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
