# Generated by Django 3.2.8 on 2021-11-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0009_alter_books_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/profiles/books-default.png', null=True, upload_to='media/profiles/'),
        ),
    ]
