# Generated by Django 3.2.8 on 2021-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0010_alter_books_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('1', 'داستان'), ('2', 'ادبیات'), ('3', 'هنر'), ('4', 'روانشناسی'), ('5', 'علوم اجتماعی و سیاسی'), ('6', 'دین و مذهب'), ('7', 'فلسفه و عرفان'), ('8', 'تاریخ'), ('9', 'کودک و نوجوان'), ('10', 'دانشگاهی')], max_length=200, null=True),
        ),
    ]
