# Generated by Django 3.2.8 on 2021-12-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmanage', '0011_books_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='owner',
        ),
    ]
