# Generated by Django 3.2.8 on 2021-12-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmanage', '0012_remove_books_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='owner',
            field=models.ForeignKey(default='mak', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
